### ISSUE TITLE
Project is not running

### ISSUE THREAD

**Issue by Jagdish-J-P** [devfinwiz/Fin-Maestro-Web#52]
After building project through DOCKER, I am navigating to browser and trying to browse http://localhost:5000/ but it is not working and because of that http://localhost:8080/ is also not working except dashbaord.

**Comment by devfinwiz** [comment]
Hi Jagdish, 
The docker branch is not in sync with the mainline. I hardly find time to maintain this project. 
I have a workaround for you. 

On the master branch, there is a directory named 'CommonFEGradio'. You can execute the driver.py inside it to get some of the key modules up. 

This alternate simplified frontend is based on Gradio. So make sure to have that before you move ahead. 

Apologies for the inconveniences!

**Comment by Jagdish-J-P** [comment]
Thanks for your response but Python is not installed in my system hence I was looking for docker version. As I am not python developer I was looking for ready to go solution.

**Comment by devfinwiz** [comment]
Will try and start work towards maintaining this repository as well... 
Currently working on other open source projects along with managing work.

**Comment by devfinwiz** [comment]
Do try the alternate solution in case you feel like taking additional efforts. 
Closing the issue for now.
